name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run composer install
        run: |
          composer clear-cache
          composer install --no-dev --prefer-dist
          
      - name: Install npm packages
        run: |
          npm ci

      # - name: Build release
      #   run: |
      #     chmod +x "${GITHUB_WORKSPACE}/bin/build-zip.sh"
      #     "${GITHUB_WORKSPACE}/bin/build-zip.sh"
          
      - name: Semantic release
        id: semantic
        uses: codfish/semantic-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
