name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build release
        run: |
          chmod +x "${GITHUB_WORKSPACE}/bin/build-zip.sh"
          "${GITHUB_WORKSPACE}/bin/build-zip.sh"
      - name: Semantic release
        id: semantic
        uses: codfish/semantic-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload release asset
        if: steps.semantic.outputs.new-release-published == 'true'
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            build/jesus-film-www.zip
