name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: montudor/action-zip@v1
      - uses: php-actions/composer@v6
        with:
          php_version: "7.3"
      - uses: AEnterprise/rsync-deploy@v1.0
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      # - name: Build release
      #   run: |
      #     chmod +x "${GITHUB_WORKSPACE}/bin/build-zip.sh"
      #     "${GITHUB_WORKSPACE}/bin/build-zip.sh"
          
      - name: Semantic release
        id: semantic
        uses: codfish/semantic-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
